Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 12068
/home/naman/TTN_Bootcamp/Python/WebD_Django/middleware_project/middleware_project/settings.py changed, reloading.
Watching for file changes with StatReloader
/home/naman/TTN_Bootcamp/Python/WebD_Django/middleware_project/middleware_project/settings.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 12068
"GET / HTTP/1.1" 200 12068
"GET / HTTP/1.1" 200 12068
"GET / HTTP/1.1" 200 12068
"GET / HTTP/1.1" 200 12068
"GET / HTTP/1.1" 200 12068
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 12068
"GET / HTTP/1.1" 200 12068
"GET / HTTP/1.1" 200 12068
"GET / HTTP/1.1" 200 12068
/home/naman/TTN_Bootcamp/Python/WebD_Django/middleware_project/middleware_app/middleware.py changed, reloading.
Watching for file changes with StatReloader
/home/naman/TTN_Bootcamp/Python/WebD_Django/middleware_project/middleware_app/middleware.py changed, reloading.
Watching for file changes with StatReloader
/home/naman/TTN_Bootcamp/Python/WebD_Django/middleware_project/middleware_app/middleware.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 12068
"GET / HTTP/1.1" 200 12068
"GET / HTTP/1.1" 200 12068
/home/naman/TTN_Bootcamp/Python/WebD_Django/middleware_project/middleware_app/middleware.py changed, reloading.
Watching for file changes with StatReloader
/home/naman/TTN_Bootcamp/Python/WebD_Django/middleware_project/middleware_project/settings.py changed, reloading.
Watching for file changes with StatReloader
Request: GET / from 127.0.0.1
"GET / HTTP/1.1" 200 12068
Request: GET / from 127.0.0.1
"GET / HTTP/1.1" 200 12068
Request: GET / from 127.0.0.1
"GET / HTTP/1.1" 200 12068
Request: GET / from 127.0.0.1
"GET / HTTP/1.1" 200 12068
/home/naman/TTN_Bootcamp/Python/WebD_Django/middleware_project/middleware_app/middleware.py changed, reloading.
Watching for file changes with StatReloader
/home/naman/TTN_Bootcamp/Python/WebD_Django/middleware_project/middleware_app/middleware.py changed, reloading.
Watching for file changes with StatReloader
Request logged: GET / from 127.0.0.1
"GET / HTTP/1.1" 200 12068
/home/naman/TTN_Bootcamp/Python/WebD_Django/middleware_project/middleware_project/settings.py changed, reloading.
Watching for file changes with StatReloader
/home/naman/TTN_Bootcamp/Python/WebD_Django/middleware_project/middleware_project/settings.py changed, reloading.
Watching for file changes with StatReloader
Request logged: GET / from 127.0.0.1
"GET / HTTP/1.1" 200 12068
Request logged: GET / from 127.0.0.1
"GET / HTTP/1.1" 200 12068
Request logged: GET / from 127.0.0.1
"GET / HTTP/1.1" 200 12068
/home/naman/TTN_Bootcamp/Python/WebD_Django/middleware_project/middleware_app/middleware.py changed, reloading.
Watching for file changes with StatReloader
/home/naman/TTN_Bootcamp/Python/WebD_Django/middleware_project/middleware_app/middleware.py changed, reloading.
Watching for file changes with StatReloader
/home/naman/TTN_Bootcamp/Python/WebD_Django/middleware_project/middleware_app/middleware.py changed, reloading.
Watching for file changes with StatReloader
/home/naman/TTN_Bootcamp/Python/WebD_Django/middleware_project/middleware_app/middleware.py changed, reloading.
Watching for file changes with StatReloader
/home/naman/TTN_Bootcamp/Python/WebD_Django/middleware_project/middleware_app/middleware.py changed, reloading.
Watching for file changes with StatReloader
/home/naman/TTN_Bootcamp/Python/WebD_Django/middleware_project/middleware_project/settings.py changed, reloading.
Watching for file changes with StatReloader
Request logged: GET / from 127.0.0.1
"GET / HTTP/1.1" 200 12068
Request logged: GET / from 127.0.0.1
"GET / HTTP/1.1" 200 12068
Request logged: GET / from 127.0.0.1
"GET / HTTP/1.1" 200 12068
Request logged: GET / from 127.0.0.1
"GET / HTTP/1.1" 200 12068
Request logged: GET / from 127.0.0.1
"GET / HTTP/1.1" 200 12068
Request logged: GET / from 127.0.0.1
"GET / HTTP/1.1" 200 12068
/home/naman/TTN_Bootcamp/Python/WebD_Django/middleware_project/middleware_app/middleware.py changed, reloading.
Watching for file changes with StatReloader
Request logged: GET / from 127.0.0.1
"GET / HTTP/1.1" 200 12068
/home/naman/TTN_Bootcamp/Python/WebD_Django/middleware_project/middleware_app/middleware.py changed, reloading.
Watching for file changes with StatReloader
/home/naman/TTN_Bootcamp/Python/WebD_Django/middleware_project/middleware_app/middleware.py changed, reloading.
Watching for file changes with StatReloader
/home/naman/TTN_Bootcamp/Python/WebD_Django/middleware_project/middleware_app/middleware.py changed, reloading.
Watching for file changes with StatReloader
/home/naman/TTN_Bootcamp/Python/WebD_Django/middleware_project/middleware_app/middleware.py changed, reloading.
Watching for file changes with StatReloader
/home/naman/TTN_Bootcamp/Python/WebD_Django/middleware_project/middleware_app/middleware.py changed, reloading.
Watching for file changes with StatReloader
/home/naman/TTN_Bootcamp/Python/WebD_Django/middleware_project/middleware_app/middleware.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Request logged: GET /admin/login/ from 127.0.0.1
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:135.0) Gecko/20100101 Firefox/135.0
Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "/home/naman/TTN_Bootcamp/Python/venv/lib/python3.10/site-packages/django/contrib/sessions/backends/base.py", line 244, in _get_session
    return self._session_cache
AttributeError: 'SessionStore' object has no attribute '_session_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/naman/TTN_Bootcamp/Python/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "/home/naman/TTN_Bootcamp/Python/venv/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
sqlite3.OperationalError: no such table: django_session

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/naman/TTN_Bootcamp/Python/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/naman/TTN_Bootcamp/Python/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/naman/TTN_Bootcamp/Python/venv/lib/python3.10/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/naman/TTN_Bootcamp/Python/venv/lib/python3.10/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/naman/TTN_Bootcamp/Python/venv/lib/python3.10/site-packages/django/contrib/admin/sites.py", line 413, in login
    if request.method == "GET" and self.has_permission(request):
  File "/home/naman/TTN_Bootcamp/Python/venv/lib/python3.10/site-packages/django/contrib/admin/sites.py", line 202, in has_permission
    return request.user.is_active and request.user.is_staff
  File "/home/naman/TTN_Bootcamp/Python/venv/lib/python3.10/site-packages/django/utils/functional.py", line 251, in inner
    self._setup()
  File "/home/naman/TTN_Bootcamp/Python/venv/lib/python3.10/site-packages/django/utils/functional.py", line 404, in _setup
    self._wrapped = self._setupfunc()
  File "/home/naman/TTN_Bootcamp/Python/venv/lib/python3.10/site-packages/django/contrib/auth/middleware.py", line 37, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "/home/naman/TTN_Bootcamp/Python/venv/lib/python3.10/site-packages/django/contrib/auth/middleware.py", line 17, in get_user
    request._cached_user = auth.get_user(request)
  File "/home/naman/TTN_Bootcamp/Python/venv/lib/python3.10/site-packages/django/contrib/auth/__init__.py", line 209, in get_user
    user_id = _get_user_session_key(request)
  File "/home/naman/TTN_Bootcamp/Python/venv/lib/python3.10/site-packages/django/contrib/auth/__init__.py", line 62, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
  File "/home/naman/TTN_Bootcamp/Python/venv/lib/python3.10/site-packages/django/contrib/sessions/backends/base.py", line 55, in __getitem__
    return self._session[key]
  File "/home/naman/TTN_Bootcamp/Python/venv/lib/python3.10/site-packages/django/contrib/sessions/backends/base.py", line 249, in _get_session
    self._session_cache = self.load()
  File "/home/naman/TTN_Bootcamp/Python/venv/lib/python3.10/site-packages/django/contrib/sessions/backends/db.py", line 55, in load
    s = self._get_session_from_db()
  File "/home/naman/TTN_Bootcamp/Python/venv/lib/python3.10/site-packages/django/contrib/sessions/backends/db.py", line 34, in _get_session_from_db
    return self.model.objects.get(
  File "/home/naman/TTN_Bootcamp/Python/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/naman/TTN_Bootcamp/Python/venv/lib/python3.10/site-packages/django/db/models/query.py", line 645, in get
    num = len(clone)
  File "/home/naman/TTN_Bootcamp/Python/venv/lib/python3.10/site-packages/django/db/models/query.py", line 382, in __len__
    self._fetch_all()
  File "/home/naman/TTN_Bootcamp/Python/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/naman/TTN_Bootcamp/Python/venv/lib/python3.10/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "/home/naman/TTN_Bootcamp/Python/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
  File "/home/naman/TTN_Bootcamp/Python/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
  File "/home/naman/TTN_Bootcamp/Python/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "/home/naman/TTN_Bootcamp/Python/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/naman/TTN_Bootcamp/Python/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/naman/TTN_Bootcamp/Python/venv/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/naman/TTN_Bootcamp/Python/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "/home/naman/TTN_Bootcamp/Python/venv/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: no such table: django_session
"GET /admin/login/?next=/admin/ HTTP/1.1" 500 197278
Request logged: GET / from 127.0.0.1
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:135.0) Gecko/20100101 Firefox/135.0
"GET / HTTP/1.1" 200 12068
Request logged: GET / from 127.0.0.1
User-Agent: Googlebot
Forbidden: /
"GET / HTTP/1.1" 403 20
/home/naman/TTN_Bootcamp/Python/WebD_Django/middleware_project/middleware_app/middleware.py changed, reloading.
Watching for file changes with StatReloader
Request logged: GET / from 127.0.0.1
User-Agent: Googlebot
Forbidden: /
"GET / HTTP/1.1" 403 21
Request logged: GET / from 127.0.0.1
User-Agent: Googlebot
Forbidden: /
"GET / HTTP/1.1" 403 21
/home/naman/TTN_Bootcamp/Python/WebD_Django/middleware_project/middleware_app/middleware.py changed, reloading.
Watching for file changes with StatReloader
/home/naman/TTN_Bootcamp/Python/WebD_Django/middleware_project/middleware_app/middleware.py changed, reloading.
Watching for file changes with StatReloader
Request logged: GET /admin/login/ from 127.0.0.1
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:135.0) Gecko/20100101 Firefox/135.0
Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "/home/naman/TTN_Bootcamp/Python/venv/lib/python3.10/site-packages/django/contrib/sessions/backends/base.py", line 244, in _get_session
    return self._session_cache
AttributeError: 'SessionStore' object has no attribute '_session_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/naman/TTN_Bootcamp/Python/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "/home/naman/TTN_Bootcamp/Python/venv/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
sqlite3.OperationalError: no such table: django_session

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/naman/TTN_Bootcamp/Python/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/naman/TTN_Bootcamp/Python/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/naman/TTN_Bootcamp/Python/venv/lib/python3.10/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/naman/TTN_Bootcamp/Python/venv/lib/python3.10/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/naman/TTN_Bootcamp/Python/venv/lib/python3.10/site-packages/django/contrib/admin/sites.py", line 413, in login
    if request.method == "GET" and self.has_permission(request):
  File "/home/naman/TTN_Bootcamp/Python/venv/lib/python3.10/site-packages/django/contrib/admin/sites.py", line 202, in has_permission
    return request.user.is_active and request.user.is_staff
  File "/home/naman/TTN_Bootcamp/Python/venv/lib/python3.10/site-packages/django/utils/functional.py", line 251, in inner
    self._setup()
  File "/home/naman/TTN_Bootcamp/Python/venv/lib/python3.10/site-packages/django/utils/functional.py", line 404, in _setup
    self._wrapped = self._setupfunc()
  File "/home/naman/TTN_Bootcamp/Python/venv/lib/python3.10/site-packages/django/contrib/auth/middleware.py", line 37, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "/home/naman/TTN_Bootcamp/Python/venv/lib/python3.10/site-packages/django/contrib/auth/middleware.py", line 17, in get_user
    request._cached_user = auth.get_user(request)
  File "/home/naman/TTN_Bootcamp/Python/venv/lib/python3.10/site-packages/django/contrib/auth/__init__.py", line 209, in get_user
    user_id = _get_user_session_key(request)
  File "/home/naman/TTN_Bootcamp/Python/venv/lib/python3.10/site-packages/django/contrib/auth/__init__.py", line 62, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
  File "/home/naman/TTN_Bootcamp/Python/venv/lib/python3.10/site-packages/django/contrib/sessions/backends/base.py", line 55, in __getitem__
    return self._session[key]
  File "/home/naman/TTN_Bootcamp/Python/venv/lib/python3.10/site-packages/django/contrib/sessions/backends/base.py", line 249, in _get_session
    self._session_cache = self.load()
  File "/home/naman/TTN_Bootcamp/Python/venv/lib/python3.10/site-packages/django/contrib/sessions/backends/db.py", line 55, in load
    s = self._get_session_from_db()
  File "/home/naman/TTN_Bootcamp/Python/venv/lib/python3.10/site-packages/django/contrib/sessions/backends/db.py", line 34, in _get_session_from_db
    return self.model.objects.get(
  File "/home/naman/TTN_Bootcamp/Python/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/naman/TTN_Bootcamp/Python/venv/lib/python3.10/site-packages/django/db/models/query.py", line 645, in get
    num = len(clone)
  File "/home/naman/TTN_Bootcamp/Python/venv/lib/python3.10/site-packages/django/db/models/query.py", line 382, in __len__
    self._fetch_all()
  File "/home/naman/TTN_Bootcamp/Python/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/naman/TTN_Bootcamp/Python/venv/lib/python3.10/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "/home/naman/TTN_Bootcamp/Python/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
  File "/home/naman/TTN_Bootcamp/Python/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
  File "/home/naman/TTN_Bootcamp/Python/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "/home/naman/TTN_Bootcamp/Python/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/naman/TTN_Bootcamp/Python/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/naman/TTN_Bootcamp/Python/venv/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/naman/TTN_Bootcamp/Python/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "/home/naman/TTN_Bootcamp/Python/venv/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: no such table: django_session
"GET /admin/login/?next=/admin/ HTTP/1.1" 500 197067
Request logged: GET / from 127.0.0.1
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:135.0) Gecko/20100101 Firefox/135.0
"GET / HTTP/1.1" 200 12068
/home/naman/TTN_Bootcamp/Python/WebD_Django/middleware_project/middleware_app/middleware.py changed, reloading.
Watching for file changes with StatReloader
Request logged: GET / from 127.0.0.1
User-Agent: curl/8.12.1
"GET / HTTP/1.1" 200 12068
/home/naman/TTN_Bootcamp/Python/WebD_Django/middleware_project/middleware_app/middleware.py changed, reloading.
Watching for file changes with StatReloader
Request logged: GET / from 127.0.0.1
User-Agent: curl/8.12.1
Forbidden: /
"GET / HTTP/1.1" 403 36
Watching for file changes with StatReloader
Request logged: GET / from 127.0.0.1
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:135.0) Gecko/20100101 Firefox/135.0
"GET / HTTP/1.1" 200 12068
Request logged: GET / from 127.0.0.1
User-Agent: curl/8.12.1
Forbidden: /
"GET / HTTP/1.1" 403 36
/home/naman/TTN_Bootcamp/Python/WebD_Django/middleware_project/middleware_app/middleware.py changed, reloading.
Watching for file changes with StatReloader
